[package]
description = "prql: query and transform data with PRQL"
name = "prql"
edition = "2021"
version = "0.2.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1"
camino = "1.1.1"
cfg-if = "1.0.0"
chrono = "0.4"
clap = { version = "3.2.3", features = ["derive"] }
datafusion = { version = "8.0.0", optional = true }
duckdb = { version = "0.4.0", features = ["bundled", "chrono"], optional = true }
env_logger = "0.9.0"
log = "0.4.17"
prql-compiler = { path = "../prql-compiler" }
tokio = "1.19"

[features]
default = ["datafusion"]
datafusion = ["dep:datafusion"]
duckdb = ["dep:duckdb"]

[package.metadata.release]
shared-version = true
tag-name = "{{version}}"
tag-prefix = ""
